server:
  build: .
  dockerfile: /etc/docker/dockerfile
  volumes:
    - ./docroot:/var/www/html
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
  ports:
    - "80:80"
    - "8080:8080"
  links:
    - mysql


mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=<your_root_password>
    - MYSQL_DATABASE=<your_database_name>
    - MYSQL_USER=<your_username>
    - MYSQL_PASSWORD=<your_password>
  volumes:
    - ./etc/mysql:/dumps
