server:
  build: .
  dockerfile: /etc/docker/dockerfile
  volumes:
    - ./docroot:/var/www/html
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
  ports:
    - "80:80"
    - "8080:8080"
  links:
    - mysql


mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=1
    - MYSQL_DATABASE=blog
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=38q8jd9f
  volumes:
    - ./etc/mysql:/dumps
